version: '3'
services:
  db_mongo:
    build: ./mongo
    ports:
      - "27017:27017"
  db_api:
    build: ./db_api
    ports:
      - "3005:3005"
    links:
      - db_mongo
  socket_api:
    build: ./socket_api
    ports:
      - "3003:3003"
    links:
      - db_api
  web_client:
    build: ./client
    ports:
      - "3000:3000"
    links:
      - socket_api